export type Project = {
  slug: string;
  size: number;
  thumbVideo: string;
  title: string;
  description: string;
  tags: string[];
  videoId: number;
  client: string;
  agency: string;
  images: string[];
  texts: string[];
};

export const projects = [
  {
    slug: "love-generation",
    size: 8,
    thumbVideo: "/projects/love-generation/thumb/love_generation-thumb.webm",
    title: "Love Generation",
    description: "Рекламный ролик \\ 30 Сек",
    tags: ["2d", "реклама"],
    videoId: 926255997,
    client: "Сбер",
    agency: "Mosaic",
    images: [
      "/projects/love-generation/term-2-1.jpg",
      "/projects/love-generation/term-2-2.jpg",
      "/projects/love-generation/term-2-3.jpg",
      "/projects/love-generation/photo_2026-03-09_15-05-06.jpg",
      "/projects/love-generation/photo_2026-03-09_15-05-17.jpg",
      "/projects/love-generation/photo_2026-03-09_15-05-20.jpg",
      "/projects/love-generation/photo_2026-03-09_15-05-22.jpg",
      "/projects/love-generation/photo_2026-03-09_15-05-23.jpg",
      "/projects/love-generation/photo_2026-03-09_15-05-25.jpg",
      "/projects/love-generation/photo_2026-03-09_15-05-27.jpg",
      "/projects/love-generation/photo_2026-03-09_15-08-25.jpg",
    ],
    texts: [
      "Для Сбера мы сделали короткий 3D-ролик про терминал оплаты улыбкой.",
      `Персонаж

        Клиент хотел оживить терминал и превратить его в эмоционального персонажа: все-таки оплата – улыбкой :)

        Мы показали характер через пластику, точный ритм (подстроились под уже готовый трек) и работу со светом.

        Добавили отсылку к культовой лампе из известной заставки (было сложно удержаться).`,
      "Проект был реализован всего за две недели — от раскадровки до финального рендера.",
    ],
  },
  {
    slug: "vk-neo",
    size: 3,
    thumbVideo: "/projects/vk-neo/thumb/NEO_pw.webm",
    title: "VK NEO",
    description: "Современный дизайн интерфейса VK с объёмными 3D элементами",
    tags: ["3d", "motion"],
    videoId: 926255997,
    client: "VK",
    agency: "",
    images: ["/projects/vk-neo/1.jpg"],
    texts: ["Инновация", "Технология"],
  },
  {
    slug: "uralsib",
    size: 4,
    thumbVideo: "/projects/uralsib/thumb/uralsib-thumb.webm",
    title: "Уралсиб",
    description: "Финансовая услуга в привлекательном визуальном исполнении",
    tags: ["2d", "реклама"],
    videoId: 926255997,
    client: "Уралсиб",
    agency: "",
    images: ["/projects/uralsib/1.jpg", "/projects/uralsib/2.jpg"],
    texts: ["Надежность", "Стабильность"],
  },
  {
    slug: "delimobil",
    size: 3,
    thumbVideo: "/projects/delimobil/thumb/delimobil-thumb.webm",
    title: "Делимобиль",
    description: "Смешная и оригинальная реклама сервиса каршеринга",
    tags: ["2d", "реклама"],
    videoId: 926255997,
    client: "Делимобиль",
    agency: "",
    images: ["/projects/delimobil/1.jpg"],
    texts: ["Мобильность", "Свобода"],
  },
  {
    slug: "mts",
    size: 6,
    thumbVideo: "/projects/mts/thumb/mts-thumb.webm",
    title: "МТС",
    description: "Телеком реклама с динамичными 3D переходами и эффектами",
    tags: ["3d", "реклама"],
    videoId: 926255997,
    client: "МТС",
    agency: "",
    images: [
      "/projects/mts/1.jpg",
      "/projects/mts/2.jpg",
      "/projects/mts/3.jpg",
    ],
    texts: ["Скорость", "Связь"],
  },
  {
    slug: "zvuk",
    size: 4,
    thumbVideo: "/projects/zvuk/thumb/zvuk-thumb.webm",
    title: "Звук",
    description:
      "Абстрактная анимация музыкального проекта с синтезирующими элементами",
    tags: ["2d", "motion"],
    videoId: 926255997,
    client: "Звук",
    agency: "",
    images: ["/projects/zvuk/1.jpg"],
    texts: ["Гармония", "Ритм"],
  },
  {
    slug: "zvuk-2",
    size: 3,
    thumbVideo: "/projects/zvuk-2/thumb/zvuk-2-thumb.webm",
    title: "Звук 2",
    description:
      "Продолжение музыкального проекта с новыми визуальными решениями",
    tags: ["2d", "motion"],
    videoId: 926255997,
    client: "Звук",
    agency: "",
    images: ["/projects/zvuk-2/1.jpg"],
    texts: ["Эволюция"],
  },
  {
    slug: "vtb-1",
    size: 4,
    thumbVideo: "/projects/vtb-1/thumb/vtb-1-thumb.webm",
    title: "ВТБ",
    description: "Финансовая институция в современном объёмном исполнении",
    tags: ["3d", "реклама"],
    videoId: 926255997,
    client: "ВТБ",
    agency: "",
    images: ["/projects/vtb-1/1.jpg", "/projects/vtb-1/2.jpg"],
    texts: ["Прогресс", "Инвестиции"],
  },
  {
    slug: "mosmuseum",
    size: 3,
    thumbVideo: "/projects/mosmuseum/thumb/mosmuseum-thumb.webm",
    title: "Музей Москвы",
    description: "Культурный проект о истории и искусстве столицы",
    tags: ["2d", "арт"],
    videoId: 926255997,
    client: "Музей Москвы",
    agency: "",
    images: ["/projects/mosmuseum/1.jpg"],
    texts: ["История", "Культура"],
  },
  {
    slug: "green-idea",
    size: 6,
    thumbVideo: "/projects/green-idea/thumb/green-idea-thumb.webm",
    title: "Green Idea",
    description: "Экологичный проект с зелёной эстетикой и плавными переходами",
    tags: ["2d", "motion"],
    videoId: 926255997,
    client: "Green Idea",
    agency: "",
    images: ["/projects/green-idea/1.jpg", "/projects/green-idea/2.jpg"],
    texts: ["Природа", "Устойчивость"],
  },
  {
    slug: "mail-ru",
    size: 4,
    thumbVideo: "/projects/mail-ru/thumb/mail-thumb.webm",
    title: "Mail.ru",
    description: "Кампания интернет-сервиса с объёмной 3D анимацией",
    tags: ["3d", "реклама"],
    videoId: 926255997,
    client: "Mail.ru",
    agency: "",
    images: ["/projects/mail-ru/1.jpg", "/projects/mail-ru/2.jpg"],
    texts: ["Коммуникация", "Сервис"],
  },
  {
    slug: "yandex-incl",
    size: 7,
    thumbVideo: "/projects/yandex-incl/thumb/ya_incl-thumb.webm",
    title: "Яндекс",
    description:
      "Технологичный проект поисковой системы с абстрактными элементами",
    tags: ["2d", "motion"],
    videoId: 926255997,
    client: "Яндекс",
    agency: "",
    images: [
      "/projects/yandex-incl/1.jpg",
      "/projects/yandex-incl/2.jpg",
      "/projects/yandex-incl/3.jpg",
    ],
    texts: ["Поиск", "Находки"],
  },
  {
    slug: "volchok",
    size: 3,
    thumbVideo: "/projects/volchok/thumb/volchok-thumb.webm",
    title: "Волчок",
    description: "Авторское произведение с игривой и динамичной анимацией",
    tags: ["2d", "авторское"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/volchok/1.jpg"],
    texts: ["Игра", "Движение"],
  },
  {
    slug: "taxi-v2",
    size: 3,
    thumbVideo: "/projects/taxi-v2/thumb/taxi-v2-thumb.webm",
    title: "Такси",
    description: "Реклама сервиса такси с быстрым темпом и динамикой",
    tags: ["2d", "реклама"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/taxi-v2/1.jpg"],
    texts: ["Скорость", "Удобство"],
  },
  {
    slug: "mansi",
    size: 3,
    thumbVideo: "/projects/mansi/thumb/mansi-thumb.webm",
    title: "Манси",
    description: "Художественный проект о культуре и традициях",
    tags: ["2d", "арт"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/mansi/1.jpg"],
    texts: ["Традиция"],
  },
  {
    slug: "stranneyshie-horiz",
    size: 3,
    thumbVideo:
      "/projects/stranneyshie-horiz/thumb/stranneyshie-horiz-thumb.webm",
    title: "Странейшие",
    description: "Авторский проект необычных идей и странных историй",
    tags: ["2d", "авторское"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/stranneyshie-horiz/1.jpg"],
    texts: ["Фантазия"],
  },
  {
    slug: "hospitality",
    size: 4,
    thumbVideo: "/projects/hospitality/thumb/hospitality-thumb.webm",
    title: "Hospitality",
    description: "Проект гостеприимства с объёмной 3D графикой",
    tags: ["3d", "motion"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/hospitality/1.jpg", "/projects/hospitality/2.jpg"],
    texts: ["Приём", "Комфорт"],
  },
  {
    slug: "i-want-to-know-everything",
    size: 6,
    thumbVideo:
      "/projects/i-want-to-know-everything/thumb/i-want-to-know-everything-thumb.webm",
    title: "I want to know",
    description: "Авторский проект о любознательности и исследованиях",
    tags: ["2d", "авторское"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: [
      "/projects/i-want-to-know-everything/1.jpg",
      "/projects/i-want-to-know-everything/2.jpg",
    ],
    texts: ["Познание", "Исследование"],
  },
  {
    slug: "presents-fest-2024",
    size: 6,
    thumbVideo:
      "/projects/presents-fest-2024/thumb/presents-fest-2024-thumb.webm",
    title: "Presents Fest",
    description: "Фестиваль подарков с праздничной и яркой атмосферой",
    tags: ["2d", "ивент"],
    videoId: 926255997,
    client: "Presents Fest",
    agency: "",
    images: [
      "/projects/presents-fest-2024/1.jpg",
      "/projects/presents-fest-2024/2.jpg",
    ],
    texts: ["Праздник", "Радость"],
  },
  {
    slug: "saint-spring-v3",
    size: 4,
    thumbVideo: "/projects/saint-spring-v3/thumb/saint-spring-v3-thumb.webm",
    title: "Saint Spring",
    description: "Весенний проект с природным 3D дизайном и мягкими цветами",
    tags: ["3d", "реклама"],
    videoId: 926255997,
    client: "Saint Spring",
    agency: "",
    images: [
      "/projects/saint-spring-v3/1.jpg",
      "/projects/saint-spring-v3/2.jpg",
    ],
    texts: ["Весна", "Обновление"],
  },
  {
    slug: "sber-high-res",
    size: 6,
    thumbVideo: "/projects/sber-high-res/thumb/sber-high-res-thumb.webm",
    title: "SBER High Res",
    description: "Высокодетальный проект банковской системы в 3D",
    tags: ["3d", "реклама"],
    videoId: 926255997,
    client: "Сбер",
    agency: "",
    images: [
      "/projects/sber-high-res/1.jpg",
      "/projects/sber-high-res/2.jpg",
      "/projects/sber-high-res/3.jpg",
    ],
    texts: ["Качество", "Детали"],
  },
  {
    slug: "sobchak",
    size: 4,
    thumbVideo: "/projects/sobchak/thumb/sobchak_thumb.webm",
    title: "Собчак",
    description:
      "Motion графика для политического проекта с модными переходами",
    tags: ["2d", "motion"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/sobchak/1.jpg"],
    texts: ["Политика"],
  },
  {
    slug: "supermarket-trollys-dream-v1",
    size: 5,
    thumbVideo:
      "/projects/supermarket-trollys-dream-v1/thumb/supermarket-trollys-dream-v1-thumb.webm",
    title: "Supermarket",
    description: "Авторское произведение о мире супермаркетов и потребления",
    tags: ["3d", "авторское"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: [
      "/projects/supermarket-trollys-dream-v1/1.jpg",
      "/projects/supermarket-trollys-dream-v1/2.jpg",
    ],
    texts: ["Сюрреализм", "Товары"],
  },
  {
    slug: "the-skin-v1",
    size: 5,
    thumbVideo: "/projects/the-skin-v1/thumb/the-skin-v1-thumb.webm",
    title: "The Skin",
    description: "Авторский проект о коже и её текстурах в 2D анимации",
    tags: ["2d", "авторское"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/the-skin-v1/1.jpg"],
    texts: ["Биология", "Текстура"],
  },
  {
    slug: "unprincipled",
    size: 3,
    thumbVideo: "/projects/unprincipled/thumb/unprincipled-thumb.webm",
    title: "Unprincipled",
    description: "Авторское бесцеремонное произведение с авангардным стилем",
    tags: ["2d", "авторское"],
    videoId: 926255997,
    client: "",
    agency: "",
    images: ["/projects/unprincipled/1.jpg"],
    texts: ["Авангард"],
  },
] satisfies Project[];

export type ProjectSlug = (typeof projects)[number]["slug"];
